project:
  type: website

website:
  title: "Portal Economia"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Macroeconomia"
        href: macroeconomia.qmd
      - text: "Política"
        href: politica.qmd
      - text: "Quem somos?"
        href: sobre.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

